Replaced asserts with exceptions
adafruit/Adafruit_CircuitPython_TLC5947 pull request #15
Opened 2019-01-08 22:19 UTC by ArthurDent62

According to issue #10

2019-01-09 16:39 UTC, caternuson commented
Looks like Travis is failing on a few pylint things. Can you check them a push a new commit with fixes.

2019-01-09 20:53 UTC, ArthurDent62 commented
Travis was lazy last night (my time) and after 15 minutes or so I gave up. Let's see if he likes my changes now.

2019-02-06 06:32 UTC, makermelissa approved these changes
Code looks good and Travis is passing now, however I don't have the hardware to test this.

2019-02-06 17:47 UTC, caternuson requested changes

2019-02-06 17:47 UTC, caternuson commented on adafruit_tlc5947.py
> +            if (val < 0) or (val > 65535):
Remove `()`s. The "pythonic" syntax is:
```python
if val < 0 or val > 65535:
```
Same for all other conditionals.

2019-02-06 17:47 UTC, caternuson commented on adafruit_tlc5947.py
> +            raise ValueError("need at least one driver; {0} is not supported.".format(num_drivers))
Capitalize first word in message.
```
Need at least...
```
Same for all messages.

2019-02-06 17:48 UTC, caternuson commented
Thanks for putting this back on the radar. I've got a few stylistic change requests.

2019-02-06 17:51 UTC, makermelissa commented
No problem. Now that you pointed those out, I agree.

2019-02-11 16:12 UTC, caternuson approved these changes

2019-02-11 16:14 UTC, merged